### ISSUE TITLE
unsatisfied payload signature sub-rule in OR rule

### ISSUE THREAD

**Issue by zry98** [adnanh/webhook#482] opened 2020-11-23 20:35 UTC
I tried to set up a webhook rule to be triggered when the payload signature is verified with any one of multiple secrets, but I found that any unsatisfied payload signature sub-rule that appears before other sub-rules in the `or rule`  will cause the parent rule be evaluated to false. 

example config:
```json
"trigger-rule": {
      "or": [
        {
          "match": {
            "type": "payload-hash-sha512",
            "secret": "secret-1",
            "parameter": {
              "source": "header",
              "name": "X-Signature"
            }
          }
        },
        {
          "match": {
            "type": "payload-hash-sha512",
            "secret": "secret-2",
            "parameter": {
              "source": "header",
              "name": "X-Signature"
            }
          }
        }
      ]
    },
```

requests signed by "secret-2" will never trigger the hook because an error will occurred:
> error evaluating hook: invalid payload signatures [...]

**Comment by moorereason** [comment] 2020-11-23 21:04
What version of `webhook` are you using?  If 2.7.0, I suspect this is a duplicate of #471.

**Comment by zry98** [comment] 2020-11-23 21:12
I've located the reason:
https://github.com/adnanh/webhook/blob/9c7f8c1ac4993c56658c4afacda5f3d40630d11e/internal/hook/hook.go#L797-L800

**Comment by zry98** [comment] 2020-11-23 21:16
> What version of `webhook` are you using? If 2.7.0, I suspect this is a duplicate of #471.

Yes, I'm using 2.7.0, please check my reply,  if `Evaluate` returned error will immediately evaluate the parent rule to false.

**Comment by moorereason** [comment] 2020-11-23 21:44
Ok.  I don't think this is a duplicate of #471 then.

I think this is, instead, a duplicate of #234.  It's been a while since I've looked at #234.  @zry98, what are you thoughts on that issue, especially [my last comment](https://github.com/adnanh/webhook/issues/234#issuecomment-369002353)?

**Comment by zry98** [comment] 2020-11-23 22:27
> Ok. I don't think this is a duplicate of #471 then.
> 
> I think this is, instead, a duplicate of #234. It's been a while since I've looked at #234. @zry98, what are you thoughts on that issue, especially [my last comment](https://github.com/adnanh/webhook/issues/234#issuecomment-369002353)?

That sounds great.

**Comment by moorereason** [comment] 2020-11-23 22:33
Closing as a duplicate of #234.

**Closed by moorereason** 2020-11-23 22:33 UTC
Labels: duplicate
