### ISSUE TITLE
Question: Dynamic Response Message echoing back SRC IP Address

### ISSUE THREAD

**Issue by donalod** [adnanh/webhook#476] opened 2020-11-17 13:29 UTC
Hello and many thanks for your app/code. Am using`Webhook version 2.7.0` and am trying to figure out how to echo back not just the headers from the client request but the source IP address i.e. "RemoteAddr" rather than "X-Forwarded-For" which is only sometimes appended by proxies etc.  

I can get the "entire-headers" to simply playback by echo'ing the passed ENV to a script and back, but it doesn't contain the SRC IP which I really want to operate on in my script (further processing) and echo back!

```
[
  {
    "id": "myip",
    "execute-command":"headers.sh",
    "command-working-directory":"/home/irldexter/webhooks",
    "include-command-output-in-response": true,
    "pass-environment-to-command":
    [
      {
        "envname": "HEADERS",
        "source": "entire-headers"
      }
    ]
  }
]
```
 
Have read the docs, am not a go programmer but happy enough in Ruby/Python etc. How can I access and echo back the client SRC IP. What am I missing here, run it as a template and access the live request via `r.RemoteAddr` somehow perhaps?

**Comment by moorereason** [comment] 2020-11-17 14:58
This is a duplicate of #312.  The remote address is not currently available to your script.

Additionally, #356 is in the works and would include the remote address, but I think #312 is a better fit for what you want.

**Closed by moorereason** 2020-11-17 14:58 UTC
Labels: duplicate

**Comment by donalod** [comment] 2020-11-17 16:03
@moorereason thanks, I was searching issues on too narrow a subset...
