### ISSUE TITLE
tail the output of the running command

### ISSUE THREAD

**Issue by simplenotezy** [adnanh/webhook#452] opened 2020-08-12 10:33 UTC
How can I tail the output of the running command? I am aware that _some_ of the commands output is returned to `supervisor.log` but that is only returned once it has failed or succeeded, and it seems that I don't get ALL the output from the shell-script.

I'd like to somehow follow the ongoing process. Is this possible?

**Comment by scottstensland** [comment] 2020-08-12 13:29
how are you deploying it ?  certainly the webook binary itself happily outputs in real time to stdout and stderr so it depends whether those are defined to get sent into separate files ...  here is my supervisord config



        cat ./devopsmicro/conf.d/webhook_supervisor.conf

	[program:webhook]
	command = /inner_home/hrothgar/src/github.com/loudthink/loudspeed/build/launch_hook.sh
	stdout_logfile = /var/log/supervisor/webhook_stdout.log
	stderr_logfile = /var/log/supervisor/webhook_stderr.log
	stdout_logfile_maxbytes = 1MB
	stderr_logfile_maxbytes = 1MB
	logfile_backups = 50
	numprocs=1
	autostart = True
	autorestart = True

	user = hrothgar
	environment=HOME="/inner_home/hrothgar"



so in my case to view ongoing traffic I would issue

   tail -f /var/log/supervisor/webhook_stdout.log

or 

     tail -f /var/log/supervisor/webhook_std*

**Comment by moorereason** [comment] 2020-08-12 15:20
This is probably a duplicate of #250.

**Closed** 2020-12-06 17:52 UTC
Labels: duplicate
